export const nodes = {
    views: {
        tracking: document.querySelector('#v-tracking'),
        deals: document.querySelector('#v-deals'),
        add: document.querySelector('#v-add'),
        notifications: document.querySelector('#v-notifications'),
        settings: document.querySelector('#v-settings'),
    },
    navItems: document.querySelectorAll('.bnav-item[data-v]'),
    productsList: document.querySelector('#productsList'),
    searchInput: document.querySelector('#searchInput'),
    searchClear: document.querySelector('#searchClear'),
    topRefreshBtn: document.querySelector('#topRefreshBtn'),
    topCopyBtn: document.querySelector('#topCopyBtn'),
    trackingStatusFilters: document.querySelector('#trackingStatusFilters'),
    detailView: document.querySelector('#detailView'),
    detailContent: document.querySelector('#detailContent'),
    detailBack: document.querySelector('#detailBack'),
    detailShare: document.querySelector('#detailShare'),
    detailDelete: document.querySelector('#detailDelete'),
    detailTopbarTitle: (document.querySelector('#d-bartitle') || document.querySelector('#detailTopbarTitle')),
    chatIdInput: document.querySelector('#chatIdInput'),
    chatIdSave: document.querySelector('#chatIdSave'),
    langRow: document.querySelector('#langRow'),
    navLabels: {
        tracking: document.querySelector('#nav-trackings'),
        deals: document.querySelector('#nav-deals'),
        add: document.querySelector('#nav-add'),
        alerts: document.querySelector('#nav-alerts'),
        settings: document.querySelector('#nav-settings'),
    },
    dealsList: document.querySelector('#dealsList'),
    dealsFabMenu: document.querySelector('#dealsFabMenu'),
    trackingFabMenu: document.querySelector('#trackingFabMenu'),
    dealsQuickFilters: document.querySelector('#dealsQuickFilters'),
    notifList: document.querySelector('#notifList'),
    asinInput: document.querySelector('#asinInput'),
    addDomains: document.querySelector('#addDomains'),
    addModeSwitch: document.querySelector('#addModeSwitch'),
    addModeHint: document.querySelector('#addModeHint'),
    addResultBox: document.querySelector('#addResultBox'),
    bulkProgress: document.querySelector('#bulkProgress'),
    bulkBarFill: document.querySelector('#bulkBarFill'),
    bulkStatus: document.querySelector('#bulkStatus'),
    serverStatsContainer: document.querySelector('#serverStatsContainer'),
    scanKpiBody: document.querySelector('#scanKpiBody'),
    keepaTokenBody: document.querySelector('#keepaTokenBody'),
    setLastscan: document.querySelector('#set-lastscan'),
    setNextscan: document.querySelector('#set-nextscan'),
    setLastscanDesc: document.querySelector('#set-lastscan-desc'),
    setNextscanDesc: document.querySelector('#set-nextscan-desc'),
    setKeepa: document.querySelector('#set-keepa'),
    setHunter: document.querySelector('#set-hunter'),
};
